apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  type: LoadBalancer
  selector:
    app: ecommerce-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  sessionAffinity: None
